/** This is an automatically generated class by FairyGUI. Please do not modify it. **/

import * as fgui from "fairygui-cc";

import UI_Com_win_num_item from "./UI_Com_win_num_item";
import UI_Com_star_item from "./UI_Com_star_item";
import UI_Btn_paytable from "./UI_Btn_paytable";
import UI_Com_speed from "./UI_Com_speed";
import UI_Com_lottory_item from "./UI_Com_lottory_item";
import UI_Btn_bet from "./UI_Btn_bet";
import UI_Com_auto from "./UI_Com_auto";
import UI_Com_reveal from "./UI_Com_reveal";
import UI_Com_bet_list from "./UI_Com_bet_list";
import UI_Com_auto_list from "./UI_Com_auto_list";
import UI_Btn_back from "./UI_Btn_back";
import UI_Btn_recharge from "./UI_Btn_recharge";
import UI_Btn_menu from "./UI_Btn_menu";
import UI_Com_menu from "./UI_Com_menu";

export default class UI_GgkView extends fgui.GComponent {

	public m_c1:fgui.Controller;
	public m_img_bg:fgui.GImage;
	public m_n84:fgui.GImage;
	public m_tf_bonus4:fgui.GTextField;
	public m_tf_bonus3:fgui.GTextField;
	public m_tf_bonus2:fgui.GTextField;
	public m_tf_bonus1:fgui.GTextField;
	public m_ani_jp:fgui.GLoader3D;
	public m_n88:fgui.GGroup;
	public m_n85:fgui.GImage;
	public m_n86:fgui.GImage;
	public m_tf_jp:fgui.GTextField;
	public m_com_win_num1:UI_Com_win_num_item;
	public m_com_win_num2:UI_Com_win_num_item;
	public m_com_win_num3:UI_Com_win_num_item;
	public m_com_win_num4:UI_Com_win_num_item;
	public m_com_win_num5:UI_Com_win_num_item;
	public m_ani_win_num:fgui.GLoader3D;
	public m_n97:fgui.GGroup;
	public m_n87:fgui.GImage;
	public m_com_star1:UI_Com_star_item;
	public m_com_star2:UI_Com_star_item;
	public m_com_star3:UI_Com_star_item;
	public m_com_star4:UI_Com_star_item;
	public m_com_star5:UI_Com_star_item;
	public m_com_star6:UI_Com_star_item;
	public m_com_star7:UI_Com_star_item;
	public m_com_star8:UI_Com_star_item;
	public m_com_star9:UI_Com_star_item;
	public m_com_star10:UI_Com_star_item;
	public m_n100:fgui.GImage;
	public m_tf_win:fgui.GTextField;
	public m_btn_paytable:UI_Btn_paytable;
	public m_tf_bet:fgui.GTextField;
	public m_tf_auto:fgui.GTextField;
	public m_com_speed:UI_Com_speed;
	public m_n101:fgui.GImage;
	public m_tf_num:fgui.GTextField;
	public m_com_lottory1:UI_Com_lottory_item;
	public m_com_lottory2:UI_Com_lottory_item;
	public m_com_lottory3:UI_Com_lottory_item;
	public m_com_lottory4:UI_Com_lottory_item;
	public m_com_lottory5:UI_Com_lottory_item;
	public m_com_lottory6:UI_Com_lottory_item;
	public m_com_lottory7:UI_Com_lottory_item;
	public m_com_lottory8:UI_Com_lottory_item;
	public m_com_lottory9:UI_Com_lottory_item;
	public m_com_lottory10:UI_Com_lottory_item;
	public m_com_lottory11:UI_Com_lottory_item;
	public m_com_lottory12:UI_Com_lottory_item;
	public m_n116:fgui.GLoader3D;
	public m_ani_lottory:fgui.GLoader3D;
	public m_btn_bet:UI_Btn_bet;
	public m_com_auto:UI_Com_auto;
	public m_com_reveal:UI_Com_reveal;
	public m_n56:fgui.GGroup;
	public m_com_bet_list:UI_Com_bet_list;
	public m_com_auto_list:UI_Com_auto_list;
	public m_n1:fgui.GImage;
	public m_btn_back:UI_Btn_back;
	public m_tf_money:fgui.GTextField;
	public m_btn_recharge:UI_Btn_recharge;
	public m_btn_menu:UI_Btn_menu;
	public m_n6:fgui.GImage;
	public m_n7:fgui.GGroup;
	public m_com_menu:UI_Com_menu;
	public static URL:string = "ui://1as7p2p8harq8x";

	public static createInstance():UI_GgkView {
		return <UI_GgkView>(fgui.UIPackage.createObject("Game", "GgkView"));
	}

	protected onConstruct():void {
		this.m_c1 = this.getControllerAt(0);
		this.m_img_bg = <fgui.GImage>(this.getChildAt(0));
		this.m_n84 = <fgui.GImage>(this.getChildAt(1));
		this.m_tf_bonus4 = <fgui.GTextField>(this.getChildAt(2));
		this.m_tf_bonus3 = <fgui.GTextField>(this.getChildAt(3));
		this.m_tf_bonus2 = <fgui.GTextField>(this.getChildAt(4));
		this.m_tf_bonus1 = <fgui.GTextField>(this.getChildAt(5));
		this.m_ani_jp = <fgui.GLoader3D>(this.getChildAt(6));
		this.m_n88 = <fgui.GGroup>(this.getChildAt(7));
		this.m_n85 = <fgui.GImage>(this.getChildAt(8));
		this.m_n86 = <fgui.GImage>(this.getChildAt(9));
		this.m_tf_jp = <fgui.GTextField>(this.getChildAt(10));
		this.m_com_win_num1 = <UI_Com_win_num_item>(this.getChildAt(11));
		this.m_com_win_num2 = <UI_Com_win_num_item>(this.getChildAt(12));
		this.m_com_win_num3 = <UI_Com_win_num_item>(this.getChildAt(13));
		this.m_com_win_num4 = <UI_Com_win_num_item>(this.getChildAt(14));
		this.m_com_win_num5 = <UI_Com_win_num_item>(this.getChildAt(15));
		this.m_ani_win_num = <fgui.GLoader3D>(this.getChildAt(16));
		this.m_n97 = <fgui.GGroup>(this.getChildAt(17));
		this.m_n87 = <fgui.GImage>(this.getChildAt(18));
		this.m_com_star1 = <UI_Com_star_item>(this.getChildAt(19));
		this.m_com_star2 = <UI_Com_star_item>(this.getChildAt(20));
		this.m_com_star3 = <UI_Com_star_item>(this.getChildAt(21));
		this.m_com_star4 = <UI_Com_star_item>(this.getChildAt(22));
		this.m_com_star5 = <UI_Com_star_item>(this.getChildAt(23));
		this.m_com_star6 = <UI_Com_star_item>(this.getChildAt(24));
		this.m_com_star7 = <UI_Com_star_item>(this.getChildAt(25));
		this.m_com_star8 = <UI_Com_star_item>(this.getChildAt(26));
		this.m_com_star9 = <UI_Com_star_item>(this.getChildAt(27));
		this.m_com_star10 = <UI_Com_star_item>(this.getChildAt(28));
		this.m_n100 = <fgui.GImage>(this.getChildAt(29));
		this.m_tf_win = <fgui.GTextField>(this.getChildAt(30));
		this.m_btn_paytable = <UI_Btn_paytable>(this.getChildAt(31));
		this.m_tf_bet = <fgui.GTextField>(this.getChildAt(32));
		this.m_tf_auto = <fgui.GTextField>(this.getChildAt(33));
		this.m_com_speed = <UI_Com_speed>(this.getChildAt(34));
		this.m_n101 = <fgui.GImage>(this.getChildAt(35));
		this.m_tf_num = <fgui.GTextField>(this.getChildAt(36));
		this.m_com_lottory1 = <UI_Com_lottory_item>(this.getChildAt(37));
		this.m_com_lottory2 = <UI_Com_lottory_item>(this.getChildAt(38));
		this.m_com_lottory3 = <UI_Com_lottory_item>(this.getChildAt(39));
		this.m_com_lottory4 = <UI_Com_lottory_item>(this.getChildAt(40));
		this.m_com_lottory5 = <UI_Com_lottory_item>(this.getChildAt(41));
		this.m_com_lottory6 = <UI_Com_lottory_item>(this.getChildAt(42));
		this.m_com_lottory7 = <UI_Com_lottory_item>(this.getChildAt(43));
		this.m_com_lottory8 = <UI_Com_lottory_item>(this.getChildAt(44));
		this.m_com_lottory9 = <UI_Com_lottory_item>(this.getChildAt(45));
		this.m_com_lottory10 = <UI_Com_lottory_item>(this.getChildAt(46));
		this.m_com_lottory11 = <UI_Com_lottory_item>(this.getChildAt(47));
		this.m_com_lottory12 = <UI_Com_lottory_item>(this.getChildAt(48));
		this.m_n116 = <fgui.GLoader3D>(this.getChildAt(49));
		this.m_ani_lottory = <fgui.GLoader3D>(this.getChildAt(50));
		this.m_btn_bet = <UI_Btn_bet>(this.getChildAt(51));
		this.m_com_auto = <UI_Com_auto>(this.getChildAt(52));
		this.m_com_reveal = <UI_Com_reveal>(this.getChildAt(53));
		this.m_n56 = <fgui.GGroup>(this.getChildAt(54));
		this.m_com_bet_list = <UI_Com_bet_list>(this.getChildAt(55));
		this.m_com_auto_list = <UI_Com_auto_list>(this.getChildAt(56));
		this.m_n1 = <fgui.GImage>(this.getChildAt(57));
		this.m_btn_back = <UI_Btn_back>(this.getChildAt(58));
		this.m_tf_money = <fgui.GTextField>(this.getChildAt(59));
		this.m_btn_recharge = <UI_Btn_recharge>(this.getChildAt(60));
		this.m_btn_menu = <UI_Btn_menu>(this.getChildAt(61));
		this.m_n6 = <fgui.GImage>(this.getChildAt(62));
		this.m_n7 = <fgui.GGroup>(this.getChildAt(63));
		this.m_com_menu = <UI_Com_menu>(this.getChildAt(64));
	}
}